### ISSUE TITLE
This Software has had the PhantomBot Copyright Removed, Please Restore

### ISSUE THREAD

**Issue by IllusionaryOne** [vesturo/PhantomBotDE#2]
Under the GPLv3 which PhantomBot is licensed under, it is indicated that the license and copyright may not be removed yet the license has been changed from GPLv3 to MIT.  I ask that the license be restored and original copyrights extended to PhantomBot.tv in the README file.  They are still present in the software when it starts, I just ask that it is also clear in the documentation in GitHub. 

For more information please refer to the GPLv3 Section 5:

5. Conveying Modified Source Versions.
You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:

a) The work must carry prominent notices stating that you modified it, and giving a relevant date.

b) The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to “keep intact all notices”.

c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.

d) If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.

At present time points a, b, and c are in being violated. 

Please restore the license and copyrights in a timely manner.  I look forward to resolving this.

Thanks!

**Comment by vesturo** [comment]
will do it ASAP, thought i changed it long ago back to GLPv3 .-.

**Comment by vesturo** [comment]
DONE!
