### ISSUE TITLE
PhantomBot's New Control Panel: Beta v1.1

### ISSUE THREAD

**Issue by DjSni** [vesturo/PhantomBotDE#6]
Hallo, 

besteht eine Möglichkeit, dass das neue Control Panel auch von dir Übersetzt wird ?

Link: https://blog.phantombot.tv/beta-1-1-of-phantombots-new-control-panel/
File: [beta-panel.zip](https://github.com/vesturo/PhantomBotDE/files/2299553/beta-panel.zip)

Gruß

**Comment by Lapotor** [comment]
Wir werden das neue Panel mit dem ersten offiziellen Release auch übersetzten.
