### ISSUE TITLE
PhantomBotDE YouTube Player

### ISSUE THREAD

**Issue by DjSni** [vesturo/PhantomBotDE#7]
Hallo,

bekomme bei dem YTP nur ein...
![screenshot_9](https://user-images.githubusercontent.com/31524614/44299766-68e38680-a2fc-11e8-87cb-6faaf4d9f406.png)

Gruß

**Comment by Lapotor** [comment]
Hallo @DjSni,
nutzt du den Standart Youtube API-Key, wenn ja könnte es evtl. verwandt mit folgendem Fehler sein: https://community.phantombot.tv/t/ytplayer-songrequest-not-opening/4894
Bitte überpfüfe dies einmal.

**Comment by DjSni** [comment]
Hallo @Lapotor,

danke für die schnelle Antwort, ich hatte den "youtubekey=xxx" nicht gesetzt.
Aber leider bleibt das Problem weiterhin bestehen.

Gruß DjSni

**Comment by vesturo** [comment]
hey @DjSni kannst du mir bitte dein komplettes log verzeichnis per mail schicken? phantombotde@gmail.com

**Comment by DjSni** [comment]
Done

**Comment by vesturo** [comment]
Hey @DjSni, 
laut dem errorlog benutzt du das beta-panel, ist das richtig?
> [handleFile()@HTTPServerCommon.java:475] HTTP Server: handleFile(): ./web/beta-panel/pages/undefined/ytplayer (No such file or directory)

Für das beta-panel bieten wir leider keinen support, weil ich persönlich keine ahnung von diesem habe.

@Lapotor hast du zufällig ne idee wie man das lösen kann?

**Comment by DjSni** [comment]
Hallo @vesturo ,

jein das Beta-Panel kann man zusätzlich nutzen... also so:

http://url:25000/beta-panel
http://url:25000/panel
http://url:25000/ytplayer

Ich könnte euch auch Zugang zum bot geben habe den 24/7 am laufen, wenn das euch weiter hilft?!

Gruß DjSni

**Comment by vesturo** [comment]
Naja der fehlercode gibt aus, dass es irgendwas mit dem beta-panel zu tun hat. könntest du mir mal nen gefallen tun und folgendes machen:

- Bot herunterfahren
- Beta-panel ordner entfernen (einfach raus verschieben woanders hin)
- bot starten
- testen ob der player lädt?

**Comment by DjSni** [comment]
Done, Problem besteht weiterhin!

im error log das gefunden:
`[08-21-2018 @ 20:43:54.996 GMT] [init.js:308] (hook.call, yTPlayerRequestCurrentSong, ./systems/youtubePlayer.js) TypeError: Cannot call method "getOwner" of null`

Gruß

**Comment by vesturo** [comment]
pass auf, ich mail dir mal 2 - 3 sachen die du bitte in dein config file einfügst. ich kann mir schon denken was es ist aber ich kann den fehler leider nicht rekonstruiren weil er bei mir schon manuell behoben ist

**Comment by DjSni** [comment]
Done, Problem besteht weiterhin!

**Comment by vesturo** [comment]
Was zum Teufel... Könntest du mir die Tage mal deinen kompletten bot als zip schicken? Dann kann ich den Code abgleichen mit meiner Developer Version. 


Mal ne dumme Frage, du hast die nötigen ports offen oder?

**Comment by vesturo** [comment]
Also auch die DBs und config und Co. Keine Sorge wird alles gelöscht hinterher

**Comment by DjSni** [comment]
Klar sind die offen :) sonnst würde das Web-Panel gar nicht tun ;)
Du hast Post...

**Comment by vesturo** [comment]
ja, das ist mir 2 stunden später dann auch aufgefallen :D ich war müde okay? haha

Jep ist angekommen, ich seh mir das gleich an und melde mich dann wieder :)

**Comment by vesturo** [comment]
soooooooooooooooooooooo...

Kurz gesagt liegt es an deinem config file / deiner Datenbank!
Hab es sowohl mit dem standard -Master Branch als auch mit meinem -Dev branch probiert, sobald ich deinen Config ordner eingefügt habe ging der player nicht mehr.

Lade mal bitte diesen Branch: [Master](https://github.com/vesturo/PhantomBotDE/archive/master.zip)

und mache nur das standard setup! also nur die nötigen keys zum laufen, keine weiteren änderungen (wie zb bindip) und kein weiteres setup außer das aktivierendes ytplayers! nutze bitte auch mal ein kürzeres / einfacheres passwort um dein aktuelles als fehlerquelle auszuschließen!

**Comment by DjSni** [comment]
Jetzt geht es... so wie es scheint, war es wegen der Datenbank...

**Comment by vesturo** [comment]
Manchmal buggen die halt rum :/
