### ISSUE TITLE
Update auf v2.4.2

### ISSUE THREAD

**Issue by DjSni** [vesturo/PhantomBotDE#9]
Hallo, 

falls ihr es noch nicht mitbekommen habt wurde am 08.11.18 das Update auf v2.4.2 released.
Seit ihr schon dran ? Ist mit einem Update zu rechnen ?

Gruß

**Comment by Lapotor** [comment]
Hallo @DjSni 
wir haben auch schon mitbekommen das die v2.4.2 erschienen ist.
Leider wird die unter diesem Repository hier zur Verfügung stehende Version nicht mehr geupdatet da wir nun an einer vollständigen Übersetzung arbeiten.
Alle Fortschritte dies bezüglich kannst du bei https://github.com/PhantomBotDE/PhantomBotDE sehen wo dann auch die neue Version erscheinen wird.

**Comment by Lapotor** [comment]
@DjSni 
Heute kam der erste Nightly Build der vollständigen Überstetzung.
Schaue dir diesen doch mal an:
https://community.phantombot.tv/t/phantombotde-vollubersetzung-complete-translation/3872/42

https://github.com/PhantomBotDE/PhantomBotDE
